#!/bin/bash
# generated by ll-helper
# set -x
set -e
function ico_width() {
    od -j6 -An -N1 -tu1 --endian=little "$1" | xargs
}
function ico_height() {
    od -j7 -An -N1 -tu1 --endian=little "$1" | xargs
}
function png_width() {
    od -j16 -N4 -tu4 -An --endian=big "$1" | xargs
}
function png_height() {
    od -j20 -N4 -tu4 -An --endian=big "$1" | xargs
}
function jpeg_sof0_offset() {
    grep $(printf "%b" "\xFF\xC0") -aob "$1" | head -n1 | grep -oP "^\d+"
}
function jpeg_width() {
    offset=$(jpeg_sof0_offset "$1")
    offset=$((offset + 7))
    od -An -j${offset} -N2 -tu2 --endian=big "$1" | xargs
}
function jpeg_height() {
    offset=$(jpeg_sof0_offset "$1")
    offset=$((offset + 5))
    od -An -j${offset} -N2 -tu2 --endian=big "$1" | xargs
}
function gif_width() {
    od -An -j6 -N2 -tu2 --endian=little "$1" | xargs
}
function gif_height() {
    od -An -j8 -N2 -tu2 --endian=little "$1" | xargs
}
function bmp_width() {
    od -An -j18 -N4 -tu4 --endian=little "$1" | xargs
}
function bmp_height() {
    od -An -j22 -N4 -tu4 --endian=little "$1" | xargs
}

function unknown_image() {
    echo "error: unknown image format:${1}" >&2
    return 1
}
function unknown_width() {
    unknown_image "$1"
}
function unknown_height() {
    unknown_image "$1"
}
function image_format() {
    file=$1
    extension=$(echo "${file##*.}" | tr '[:upper:]' '[:lower:]')
    case "$extension" in
    jpg | jpeg)
        echo "jpeg"
        ;;
    png)
        echo "png"
        ;;
    gif)
        echo "gif"
        ;;
    bmp)
        echo "bmp"
        ;;
    ico)
        echo "ico"
        ;;
    svg)
        echo "svg"
        ;;
    *)
        echo "unknown"
        ;;
    esac
}
function image_width() {
    format=$(image_format "$1")
    ${format}_width "$1"
}

function image_height() {
    format=$(image_format "$1")
    ${format}_height "$1"
}
function copy_image() {
    icon_src=$1
    icon_size=$2
    icon_name=$3
    icon_dir=$PREFIX/share/icons/hicolor/${icon_size}/apps
    icon_path="$icon_dir/$icon_name"
    if [ -e "$$icon_path" ]; then
        return
    fi
    mkdir -p "$icon_dir"
    cp -afv "$icon_src" "$icon_path"

}
function setup_image() {
    # dde只搜索.svg和.png
    icon_src=$1
    icon_name=$2
    format=$(image_format "$icon_src")
    if [ "$format" == "svg" ]; then
        copy_image "$icon_src" scalable "${icon_name}.svg"
        return
    fi
    width=$(image_width "$icon_src")
    if [[ $((width & (width - 1))) -eq 0 ]]; then
        copy_image "$icon_src" "${width}x${width}" "${icon_name}.png"
        return
    fi
    size=16
    for i in 16 24 32 48 128 256 512; do
        current=$((2 ** i))
        if [[ "$current" -le "$width" ]]; then
            size=$current
        else
            break
        fi
    done
    copy_image "$icon_src" "${size}x${size}" "${icon_name}.png"
}

setup_image "$1" "$2"
